name: DockerImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  prediction:
    runs-on: ubuntu-latest
    container: adsoft/ai-ops:latest

    steps:
    - uses: actions/checkout@v2
    
    - name: run python program 
      run: python linear.py
    
    - name: list files
      run: ls -la  
 
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
